### ISSUE TITLE
Produce a documentation

### ISSUE THREAD

**Issue by arteymix** [antono/valum#30]
[Read the Docs](https://readthedocs.org/) is a nice service for hosting documentation and would only require to setup a GitHub hook.

I think that we should produce a user guide in Markdown and an api documentation using the valadoc tool.

@antono if you could enable the hook in the repo settings, it would be amazing!

**Comment by antono** [comment]
Added ReadTheDocs hook.

**Comment by antono** [comment]
http://valum.readthedocs.org/en/latest/ :)

**Comment by arteymix** [comment]
Good, I did a setup for MkDocs in fastcgi and splitted the commit to get the basic setup for the master branch.

The index points at the `README.md` file and the LGPL license is included!
