### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by arteymix** [antono/valum#33]
Cookies are working, so we should look forward session implementation.

The main issue about it is its persistency. Most web servers offers that service, so I believe it's best that we do not implement the session storage ourselves.

* [Apache mod_session](http://httpd.apache.org/docs/2.4/fr/mod/mod_session.html)

Now I think we should gather information about server-side session implementation to take the right design decision.

**Comment by arteymix** [comment]
Session seem to be an integrating part of HTTP request in web server implementation, so I think we could implement it in the VSGI specification.

On CGI, it can be extracted from `HTTP_SESSION` environment variable.

The SoupServer can store them in-memory.

**Comment by arteymix** [comment]
The implementation is done, I will write some tests on my free time!

**Comment by antono** [comment]
In memory session will not scale behind load balancer but It will work for small apps :) Most scalable option is encrypted cookie to store session id.

**Comment by arteymix** [comment]
The VSGI should provide an abstraction over how server handle session and provide one only if it's built-in.

Technically, if the server does not support session (`mod_session` not installed on Apache for example) you should rely on an external service (Redis, memcached, ...) and a cookie to do so.

The point of using an in-memory session for Soup is that we know it's not production-ready (or maybe?)

**Comment by arteymix** [comment]
I think I have a good idea for session (but also cookies, cache and other services). We could make reusable and optional components that would provide facilities for the low-level VSGI call.

Right now, I have a `Cache` and `Session` builder prototype and a simple `Cookies` handler a82cedd. I think that this approach respects the micro-framework essence. I am also thinking about a validation module, but I need to see around if it does not already exists.

Cache and session are particular as many implementations can coexist (memcached, redis, in-memory, ...), so we could write simple implementations based on multiple backend sharing the same interface.

The important thing is to keep a minimal amount of dependencies, especially since we will have to depend on a client library per implementation. We could make these dependencies optional and build consequently.

This is really going to make people life easier as they will only want to build Valum with the dependencies they need for their projects.

**Comment by arteymix** [comment]
I will open an issue for components and probably a PR if it goes well!

This issue is about VSGI native session implementation that some HTTP server provide.

**Comment by arteymix** [comment]
Okay, I just need to test it on FastCGI and it will get merged.

**Comment by arteymix** [comment]
Discussion should continue on #46
