### ISSUE TITLE
Keep the core clean

### ISSUE THREAD

**Issue by arteymix** [antono/valum#4]
I think Valum should provide only basic routing and request-response.

We would gain much more from having a slick micro-framework upon which anyone could build the full-featured framework he likes. This is how Node.js work: by providing basic abstraction and letting framework like Express.js handle application development.

The key part of Valum would be to provide a awesome routing system and integration in CGI, SGI, and other web server implementation. 

We should move the templating facilities, scripting engines and all other fancy stuff in separate libraries that end-developer could or not include in its web application.

However, I really see from a good eye to have an included templating solution like Ctpl, so we should ship it with Valum.

Ultimately, a Valum application would be combined with other C/Vala libraries to handle database persistency, Redis or any external services.

**Comment by arteymix** [comment]
This is good now as the project is splitted in two source trees (app and src) and that _most of _not directly related to the framework features has been moved to the app folder.

The build system allow us to define distinct dependencies for libvalum and the valum executable.

I think it's good for now!

Maybe we should make an examples folder that would contain multiple standalone examples instead of having everything in a single one.

**Comment by antono** [comment]
Sure. Single file per example would be great!

**Comment by arteymix** [comment]
Yeah, I already worked this out in the `fastcgi` branch!

**Comment by arteymix** [comment]
Every example has its own `wscript_build` file and dependencies.

**Comment by arteymix** [comment]
Okay, this is cool to me, the `fastcgi` branch fixes this issue by introducing examples.

Also, examples will have their own `wscript_configure` to check for their specific dependencies.
